### ISSUE TITLE
when I open  VetidOTC.exe

### ISSUE THREAD

**Issue by noping5811** [vetid/otcfix#1]
when I open  VetidOTC.exe everytime donwloads 3 files 0.5 MB, 15 MB and 45MB and doesnt work why?

**Comment by Tripticon84** [comment]
same problem

**Comment by vetid** [comment]
Sorry, that you had to wait this long.

So, we could understand your issue a bit further.

Contact Support on the Discord:
https://discord.gg/tUJsJgX
