### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by MainreX** [vetid/otcfix#2]
[+] downloading fix files

[+] downloading file 1 (0.5MB)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception was thrown by the target of an invocation. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
    location: System.Net.WebClient.DownloadFile (Uri address, String fileName)
    --- End of inner exception stack trace ---
    location: 4E814654.282A6D23 (Exception 3B6C6155)
    Location: 4E814654.424433B6 (Object [] 27CB37C4, Int32 79FE4853)
    location: ManualMapInjection.Program.Main (String [] args)

**Comment by vetid** [comment]
It is currently outdated, because it uses a download link that doesn't exist anymore.
+ the method may have been fixed aswell, on top of that.
Join our Discord, to get info about a release faster though.
