### ISSUE TITLE
Why is that?

### ISSUE THREAD

**Issue by hani-lengxi** [vetid/otcfix#3]
![Uploading QQ截图2022120921
![QQ截图20221209211615](https://user-images.githubusercontent.com/82372239/206712095-2138fb8e-288e-4a5f-8c41-4e286d310505.png)
1558.png…]()

**Comment by hani-lengxi** [comment]
![QQ截图20221209211558](https://user-images.githubusercontent.com/82372239/206712235-42050d7e-33f8-4fcc-93d3-0016bb583d5c.png)

**Comment by hani-lengxi** [comment]
![QQ截图20221209211615](https://user-images.githubusercontent.com/82372239/206712268-675dfea2-fcd1-4896-95fc-4fcfc691cfdb.png)

**Comment by vetid** [comment]
The website that had the fix files download hosted on it, doesn’t exist anymore.
This release is 2 years old.

**Comment by hani-lengxi** [comment]
Can you show me how to fix it

**Comment by hani-lengxi** [comment]
Or if there is a link to the tutorial I would appreciate it if there is
